version: '2'
services:
    a5backend-app:
        image: a5backend
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://a5backend-mysql:3306/a5backend?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    a5backend-mysql:
        extends:
            file: mysql.yml
            service: a5backend-mysql
